### ISSUE TITLE
导入 ChatCompletion报错。

### ISSUE THREAD

**Issue by edica02** [jesselau76/ebook-GPT-translator#15]
File "text_translation.py", line 229, in translate_text
    completion = openai.ChatCompletion.create(
AttributeError: module 'openai' has no attribute 'ChatCompletion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "text_translation.py", line 363, in <module>
    translated_short_text = translate_and_store(short_text)
  File "text_translation.py", line 281, in translate_and_store
    translated_text = translate_text(text)
  File "text_translation.py", line 253, in translate_text
    completion = openai.ChatCompletion.create(
AttributeError: module 'openai' has no attribute 'ChatCompletion'

怎么解决啊大佬。

**Comment by jesselau76** [comment]
可能是openai的python导入问题。或者api key停用了。
参考https://github.com/jesselau76/ebook-GPT-translator/issues/7 试试重装openai,或换环境试试
